name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'users/**'
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '7.0.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore Sample.sln

      - name: Build
        run: dotnet build Sample.sln --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test ./SimpleWebApi.Tests/SimpleWebApi.Tests.csproj

      - name: Security Check (optional)
        run: dotnet format Sample.sln --verify-no-changes

  deploy-dev:
    name: Deploy to Development
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'users/')
    environment:
      name: Development
      url: https://dev.example.com
    steps:
      - name: Deploy to Dev
        run: echo "✅ Deploying to Development"

  deploy-qa:
    name: Deploy to QA
    needs: deploy-dev
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment:
      name: QA
      url: https://qa.example.com
    steps:
      - name: Deploy to QA
        run: echo "🚀 Deploying to QA"

  deploy-prod:
    name: Deploy to Production
    needs: deploy-qa
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment:
      name: Production
      url: https://prod.example.com
    steps:
      - name: Deploy to Production
        run: echo "🚀 Deploying to Production"
