name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '7.0.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore Sample.sln

      - name: Build
        run: dotnet build Sample.sln --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test ./SimpleWebApi.Tests/SimpleWebApi.Tests.csproj

      - name: Security Check (optional)
        run: dotnet format --verify-no-changes

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'Production' || 'Development' }}
      url: https://example.com
    steps:
      - name: Echo Deployment
        run: echo "Deploying to ${{ github.ref_name == 'main' && 'Production' || 'Development' }}"
